# 配置服务器的端口，通常设置为8888:
server:
  port: 8888

spring:
  application:
    name: config-server
  # 从文件读取配置文件时，Config Server 激活的profile必须设定为native
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # 设置配置文件的搜索路径
          search-locations: file:./config-repo, file:../config-repo, file:../../config-repo